name: Deploy GitHub Pages

on:
  push:
    branches: ["main"] # main 브랜치에 코드가 push되면 작동
  workflow_dispatch:   # 수동 실행도 가능하게 설정

# Pages 배포를 위한 권한 설정
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # 웹앱 루트 디렉토리 (HTML/JS가 있는 위치)
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
